version: "3.9"
services:
  postgres:
    container_name: bankdb
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=simple_bank
  api:
    container_name: bankapi
    build:
      context: ../
      dockerfile: build/package/Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      - postgres
    entrypoint:
      [
        "/usr/app/scripts/wait-for.sh",
        "postgres:5432",
        "--",
        "/usr/app/scripts/start.sh"
      ]
    command: [ "/usr/app/main" ]
